# Generated by Django 4.2 on 2023-11-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PK')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('id_parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PK')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
                ('dt_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('dt_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('id_folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.folder')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_criacao', to=settings.AUTH_USER_MODEL, verbose_name='Criado por: ')),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por: ')),
            ],
        ),
    ]
