# Generated by Django 4.2 on 2023-11-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Seq.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.folder', verbose_name='Pasta'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Sequência'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id_parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.folder'),
        ),
    ]
