# Generated by Django 4.2 on 2023-10-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_directory_id_parent_dir'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directory',
            new_name='Folder',
        ),
    ]
