# Generated by Django 4.2 on 2023-10-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='file'),
        ),
    ]
