# Generated by Django 4.2 on 2023-10-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0005_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por: '),
        ),
    ]
